/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatatasRouteImport } from './routes/batatas'
import { Route as BebidasRouteImport } from './routes/bebidas'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SalgadosRouteImport } from './routes/salgados'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatatasRoute = BatatasRouteImport.update({
  id: '/batatas',
  path: '/batatas',
  getParentRoute: () => rootRouteImport,
} as any)
const BebidasRoute = BebidasRouteImport.update({
  id: '/bebidas',
  path: '/bebidas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SalgadosRoute = SalgadosRouteImport.update({
  id: '/salgados',
  path: '/salgados',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batatas': typeof BatatasRoute
  '/bebidas': typeof BebidasRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/salgados': typeof SalgadosRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batatas': typeof BatatasRoute
  '/bebidas': typeof BebidasRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/salgados': typeof SalgadosRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batatas': typeof BatatasRoute
  '/bebidas': typeof BebidasRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/salgados': typeof SalgadosRoute
  '/pedido/$id': typeof PedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batatas'
    | '/bebidas'
    | '/carrinho'
    | '/checkout'
    | '/salgados'
    | '/pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batatas'
    | '/bebidas'
    | '/carrinho'
    | '/checkout'
    | '/salgados'
    | '/pedido/$id'
  id:
    | '__root__'
    | '/'
    | '/batatas'
    | '/bebidas'
    | '/carrinho'
    | '/checkout'
    | '/salgados'
    | '/pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatatasRoute: typeof BatatasRoute
  BebidasRoute: typeof BebidasRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  SalgadosRoute: typeof SalgadosRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batatas': {
      id: '/batatas'
      path: '/batatas'
      fullPath: '/batatas'
      preLoaderRoute: typeof BatatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bebidas': {
      id: '/bebidas'
      path: '/bebidas'
      fullPath: '/bebidas'
      preLoaderRoute: typeof BebidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salgados': {
      id: '/salgados'
      path: '/salgados'
      fullPath: '/salgados'
      preLoaderRoute: typeof SalgadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatatasRoute: BatatasRoute,
  BebidasRoute: BebidasRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  SalgadosRoute: SalgadosRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
